module.exports = {
  apps: [
    {
      name: 'hocvienbigdipper-frontend',
      script: 'server.js',
      cwd: '/var/www/hocvienbigdipper/frontend/.next-standalone',
      instances: 'max',
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      node_args: '--enable-source-maps',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NEXT_PUBLIC_API_URL: 'https://api.hocvienbigdipper.com',
        NEXT_PUBLIC_SITE_URL: 'https://hocvienbigdipper.com',
      },
      error_file: '/var/log/hocvienbigdipper/frontend-error.log',
      out_file: '/var/log/hocvienbigdipper/frontend-out.log',
      log_file: '/var/log/hocvienbigdipper/frontend-combined.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_restarts: 10,
      min_uptime: '10s',
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      name: 'hocvienbigdipper-backend',
      script: 'dist/server.js',
      cwd: '/var/www/hocvienbigdipper/backend',
      instances: 2,
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      node_args: '--enable-source-maps',
      env: {
        NODE_ENV: 'production',
        HOST: '0.0.0.0',
        PORT: 5000,
        FRONTEND_URL: 'https://hocvienbigdipper.com',
      },
      error_file: '/var/log/hocvienbigdipper/backend-error.log',
      out_file: '/var/log/hocvienbigdipper/backend-out.log',
      log_file: '/var/log/hocvienbigdipper/backend-combined.log',
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_restarts: 10,
      min_uptime: '10s',
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
  ],

  deploy: {
    production: {
      user: 'deploy',
      host: 'hocvienbigdipper.com',
      ref: 'origin/main',
      repo: 'git@github.com:your-username/hocvienbigdipper.git',
      path: '/var/www/hocvienbigdipper',
      'post-deploy': 'cd current && ./scripts/deploy.sh',
      'pre-deploy-local': '',
      'post-setup': '',
    },
  },
};
